package fpcandroid.firstperformance.demo.firstperformance;

/**
 * Created by mtrussell on 6/30/15.
 * Copyright First Performance Corporation
 *
 * DO NOT EDIT THIS FILE
 */
public interface DemoInterface {
    void setCountdownText(Integer count);
}